// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using learndotnet.Data;

namespace learndotnet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241013105811_NewDataAdded")]
    partial class NewDataAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("learndotnet.Models.GameModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Device");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("GameTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Device = "mobile",
                            Name = "PUBG"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
